### ISSUE TITLE
key [nPropane] was not found in string_to_index_map in JSONFluidLibrary

### ISSUE THREAD

**Issue by bigoper** [portyanikhin/SharpProp#125]
# INTRO
- I'm trying to build a Mixture (of 7 compositions)
- I'm getting an error when adding the `nPropane` to the mix.

# TROUBLESHOOTING
- Changing the order of the compositions in the mix yields no changes
- The `nButane` yields no errors

# ENV
```js
SharoProp 5.0.0
```

# CODE
```cs
var mixture = new Mixture(
      new List<FluidsList> { 
            FluidsList.Methane, 
            FluidsList.Ethane, 
            FluidsList.nPropane, 
            FluidsList.IsoButane, 
            FluidsList.nButane, 
            FluidsList.Nitrogen, 
            FluidsList.CarbonDioxide
        },
        new List<Ratio> { 
            (85.5267271).Percent(), 
            (0.270918).Percent(), 
            (0.02083985).Percent(),
            (0.01041992).Percent(),
            (0.01041992).Percent(),
            (6.75211003).Percent(),
            (7.40856518).Percent()
        })
            .WithState(
                Input.Pressure((1074).PoundsForcePerSquareInch()),
                Input.Temperature((75.2).DegreesFahrenheit())
            );
```

# ERROR
```cs
System.ApplicationException
  HResult=0x80131600
  Message=key [nPropane] was not found in string_to_index_map in JSONFluidLibrary
  Source=SharpProp
  StackTrace:
   at SharpProp.AbstractState.Factory(String backend, String fluidNames)
   at SharpProp.Mixture..ctor(IEnumerable`1 fluids, IEnumerable`1 fractions)
   at SharpProp_Core.MainForm.buttonTesting_Click(Object sender, EventArgs e) in C:\Users\aviivgi\Documents\Projects\Project EMC2PDFA\EMMC2PDFA - REFPROP\MainForm.cs:line 907

  This exception was originally thrown at this call stack:
    [External Code]
    SharpProp_Core.MainForm.buttonTesting_Click(object, System.EventArgs) in MainForm.cs
```

# RESOURCES
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/7744385/218776829-eb21665e-8546-4437-9216-f68df88c2fd4.png">

**Comment by bigoper** [comment]
# NOTES
It seems like if I use `R290` instead of `nPropane`, the code will execute with no errors.

**Comment by portyanikhin** [comment]
Hello, @bigoper!

Thank you for helping me find the bug!
I've already found out what the reason is. I will fix it in the next version (soon).

Now it is worth using R290 for this case.

**Comment by bigoper** [comment]
@portyanikhin 
Thank you for this awesome project and for your prompt response!
